/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description 서버 상태 확인용
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User Me
         * @description Get current authenticated user's information.
         */
        get: operations["read_current_user_me_api_v1_auth_login_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Access Token
         * @description OAuth2 compatible token login, get an access token for future requests
         */
        post: operations["login_access_token_api_v1_auth_login_access_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh access token using a refresh token
         */
        post: operations["refresh_token_api_v1_auth_login_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout: Blacklist the access token AND refresh token (if provided).
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/discord/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discord Authorize Url
         * @description Returns the Discord OAuth2 authorization URL. Frontend can redirect to this URL.
         */
        get: operations["discord_authorize_url_api_v1_auth_discord_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/discord/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discord Exchange Code
         * @description Exchange Discord OAuth code to local tokens.
         *     The `redirect_uri` should match the one used when initiating OAuth.
         */
        post: operations["discord_exchange_code_api_v1_auth_discord_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Portfolio
         * @description 내 포트폴리오(보유 자산 및 현금)를 조회합니다.
         */
        get: operations["get_my_portfolio_api_v1_me_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Watchlist
         * @description 내 관심 종목 리스트 및 간략 시세 조회
         */
        get: operations["get_my_watchlist_api_v1_me_watchlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/watchlist/{ticker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add To My Watchlist
         * @description 관심 종목 등록
         */
        post: operations["add_to_my_watchlist_api_v1_me_watchlist__ticker_id__post"];
        /**
         * Remove From My Watchlist
         * @description 관심 종목 해제
         */
        delete: operations["remove_from_my_watchlist_api_v1_me_watchlist__ticker_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wallet/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Wallet History
         * @description 내 지갑(현금) 변동 내역을 조회합니다.
         *     (입출금, 배당, 수수료, 파산 청산 등)
         */
        get: operations["get_my_wallet_history_api_v1_me_wallet_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Pnl
         * @description 특정 기간 동안의 실현 손익(Realized PnL) 합계를 조회합니다.
         */
        get: operations["get_my_pnl_api_v1_me_pnl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Orders
         * @description 내 전체 주문 내역을 조회합니다.
         */
        get: operations["get_my_orders_api_v1_me_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/orders/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Open Orders
         * @description 내 미체결(PENDING) 주문 내역을 조회합니다.
         */
        get: operations["get_my_open_orders_api_v1_me_orders_open_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Order Detail
         * @description 특정 주문의 상세 정보를 조회합니다. (본인 주문만 가능)
         */
        get: operations["get_my_order_detail_api_v1_me_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/bankruptcy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * File Bankruptcy
         * @description [파산 신청]
         *     - 조건: 총 자산(현금 + 포트폴리오 평가액)이 0 이하일 때만 가능
         *     - 보유 자산(Portfolio) 모두 시장가에 청산
         *     - 미체결 주문(Pending Order) 취소
         *     - 유저 상태: 파산(is_bankrupt=True), 파산 횟수 증가
         *     - HUMAN ETF 발행: 본인 주식 1,000주 지급
         */
        post: operations["file_bankruptcy_api_v1_me_bankruptcy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Order
         * @description 주문 접수 API (Non-blocking)
         *     DB를 건드리지 않고 Queue에 넣기만 함.
         */
        post: operations["create_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Order
         * @description PENDING 상태의 지정가 주문을 취소합니다. 주문 소유자만 취소 가능.
         */
        post: operations["cancel_order_api_v1_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Status
         * @description 현재 각 시장(KRX, US, CRYPTO)의 운영 상태를 반환합니다.
         */
        get: operations["get_market_status_api_v1_market_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tickers
         * @description 상장된 모든 활성 종목 리스트를 조회합니다.
         */
        get: operations["get_tickers_api_v1_market_tickers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Tickers
         * @description 종목 이름 또는 심볼로 종목을 검색합니다.
         */
        get: operations["search_tickers_api_v1_market_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/candles/{ticker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candles
         * @description 특정 종목의 과거 차트 데이터(분봉/일봉)를 조회합니다.
         *     - interval: "1m" (분봉) 또는 "1d" (일봉)
         */
        get: operations["get_candles_api_v1_market_candles__ticker_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/orderbook/{ticker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Orderbook
         * @description 특정 종목의 내부 호가창(Orderbook)을 조회합니다.
         *     참가자들의 미체결 지정가 주문(LIMIT)을 집계하여 보여줍니다.
         */
        get: operations["get_orderbook_api_v1_market_orderbook__ticker_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/price/{ticker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ticker Current Price
         * @description 특정 티커의 현재 시장 가격을 조회합니다.
         *     인증: Bearer Token (로그인) 또는 X-API-Key 모두 지원.
         */
        get: operations["get_ticker_current_price_api_v1_market_price__ticker_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Movers Endpoint
         * @description 오늘의 등락률 상위(gainers) / 하위(losers) 종목을 조회합니다.
         */
        get: operations["get_movers_endpoint_api_v1_market_movers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trending Endpoint
         * @description 현재 거래가 가장 활발한(거래대금 급증) 종목을 조회합니다.
         */
        get: operations["get_trending_endpoint_api_v1_market_trending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Seasons
         * @description 모든 시즌 목록을 조회합니다.
         */
        get: operations["get_seasons_api_v1_rankings_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings/hall-of-fame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hall Of Fame
         * @description 명예의 전당: 각 부문별 1위 유저를 모아서 반환합니다. (현재 활성 시즌 기준)
         */
        get: operations["get_hall_of_fame_api_v1_rankings_hall_of_fame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings/{ranking_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rankings
         * @description 랭킹 조회 API
         *     - pnl: 실현 손익 순 (고수)
         *     - loss: 실현 손실 순 (흑우 - total_loss 내림차순)
         *     - volume: 거래 횟수 순 (단타왕)
         *     - win_rate: 승률 순 (익절/전체, 10회 이상 거래자만)
         *     - fees: 수수료 기부왕
         *     - night: 야행성 (미장 좀비)
         *     - profit_factor: 손익비 (총수익/총손실)
         *     - market_ratio: 성격 급한 정도 (시장가비율)
         */
        get: operations["get_rankings_api_v1_rankings__ranking_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/human/bailout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Bailout
         * @description [긴급 구제 금융 신청]
         *     - 조건: 파산 상태이며, 발행한 Human ETF 주식이 팔리지 않음.
         *     - 효과: 시스템 봇이 평가 금액으로 전량 매수.
         */
        post: operations["request_bailout_api_v1_human_bailout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/human/ipo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Ipo
         * @description [IPO] 자신의 지분을 주식으로 발행합니다.
         *     - HUMAN_{USER_ID} 티커 생성
         *     - 입력받은 수량만큼 발행하여 본인 지갑에 입고
         *     - 파산자는 배당률 50% 이상 필수
         */
        post: operations["create_ipo_api_v1_human_ipo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/human/burn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Burn Shares
         * @description [소각] 보유한 자사주(Human ETF)를 소각합니다.
         *     - 모든 유통 주식을 소각하면 상장 폐지 및 파산 해제(해방)됩니다.
         */
        post: operations["burn_shares_api_v1_human_burn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description 전체 유저 목록을 조회합니다.
         */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update User Ban Status
         * @description 유저 활성 상태 변경 (Ban/Unban)
         *     - is_active=False: 차단 (로그인 불가)
         *     - is_active=True: 정상
         */
        put: operations["update_user_ban_status_api_v1_admin_users__user_id__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/bankruptcy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Force Bankruptcy
         * @description [관리자 권한] 유저를 강제로 파산시킵니다. (자산 조건 무시)
         */
        post: operations["admin_force_bankruptcy_api_v1_admin_users__user_id__bankruptcy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/notice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create System Notice
         * @description 시스템 전체 공지사항을 설정합니다.
         */
        post: operations["create_system_notice_api_v1_admin_notice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/fee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trading Fee
         * @description 현재 거래 수수료율을 조회합니다.
         *     Redis에 값이 없으면 기본값(0.001, 0.1%)을 반환합니다.
         */
        get: operations["get_trading_fee_api_v1_admin_fee_get"];
        /**
         * Update Trading Fee
         * @description 거래 수수료율을 수정합니다.
         */
        put: operations["update_trading_fee_api_v1_admin_fee_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Test Price Admin
         * @description [관리자용] 특정 코인의 가격을 강제로 변경하고 이벤트를 발생시킵니다.
         *     이 API를 호출하면 limit_matcher가 즉시 반응하여 지정가 주문을 체결합니다.
         */
        post: operations["set_test_price_admin_api_v1_admin_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/alerts/whale-threshold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Whale Threshold
         * @description 고래 알림 임계치(KRW)를 조회합니다.
         */
        get: operations["get_whale_threshold_api_v1_admin_alerts_whale_threshold_get"];
        /**
         * Put Whale Threshold
         * @description 고래 알림 임계치(KRW)를 업데이트합니다.
         */
        put: operations["put_whale_threshold_api_v1_admin_alerts_whale_threshold_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_admin_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/templates/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_api_v1_admin_templates__key__get"];
        /** Put Template */
        put: operations["put_template_api_v1_admin_templates__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Ticker
         * @description 새로운 종목을 추가합니다. ID는 `id` 필드를 통해 직접 지정합니다.
         */
        post: operations["create_ticker_api_v1_admin_tickers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tickers/{ticker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Ticker
         * @description 종목 정보를 수정합니다.
         */
        put: operations["update_ticker_api_v1_admin_tickers__ticker_id__put"];
        post?: never;
        /**
         * Delete Ticker
         * @description 종목을 삭제합니다. (주의: 연관 데이터가 있으면 에러 발생 가능)
         */
        delete: operations["delete_ticker_api_v1_admin_tickers__ticker_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_api_v1_api_keys__get"];
        put?: never;
        /** Create Api Key */
        post: operations["create_api_key_api_v1_api_keys__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key */
        delete: operations["revoke_api_key_api_v1_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{key_id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Api Key */
        post: operations["rotate_api_key_api_v1_api_keys__key_id__rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile Endpoint
         * @description 특정 유저의 프로필 정보를 조회합니다. (닉네임, 뱃지, 수익률)
         */
        get: operations["get_user_profile_endpoint_api_v1_users__user_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreateRequest */
        ApiKeyCreateRequest: {
            /** Name */
            name?: string | null;
        };
        /** ApiKeyCreateResponse */
        ApiKeyCreateResponse: {
            /**
             * Key Id
             * Format: uuid
             */
            key_id: string;
            /** Api Key */
            api_key: string;
            /** Name */
            name?: string | null;
        };
        /** ApiKeyItem */
        ApiKeyItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
            /** Key Prefix */
            key_prefix: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at?: string | null;
        };
        /** ApiKeyListResponse */
        ApiKeyListResponse: {
            /** Items */
            items: components["schemas"]["ApiKeyItem"][];
        };
        /** ApiKeyRotateResponse */
        ApiKeyRotateResponse: {
            /**
             * Key Id
             * Format: uuid
             */
            key_id: string;
            /** Api Key */
            api_key: string;
        };
        /** AssetResponse */
        AssetResponse: {
            /** Ticker Id */
            ticker_id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /**
             * Quantity
             * Format: decimal
             */
            quantity: string;
            /**
             * Average Price
             * Format: decimal
             */
            average_price: string;
            /**
             * Current Price
             * Format: decimal
             */
            current_price: string;
            /**
             * Total Value
             * Format: decimal
             */
            total_value: string;
            /**
             * Profit Rate
             * Format: decimal
             */
            profit_rate: string;
        };
        /** Body_login_access_token_api_v1_auth_login_access_token_post */
        Body_login_access_token_api_v1_auth_login_access_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** BurnCreate */
        BurnCreate: {
            /**
             * Quantity
             * @description 소각할 주식 수
             */
            quantity: number | string;
        };
        /** CandleResponse */
        CandleResponse: {
            /** Ticker Id */
            ticker_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "KRW" | "USD";
        /** CurrentPriceResponse */
        CurrentPriceResponse: {
            /** Ticker Id */
            ticker_id: string;
            /** Price */
            price?: string | null;
            /** Message */
            message?: string | null;
        };
        /** DiscordExchangeRequest */
        DiscordExchangeRequest: {
            /** Code */
            code: string;
            /** Redirect Uri */
            redirect_uri?: string | null;
        };
        /** FeeUpdate */
        FeeUpdate: {
            /**
             * Fee Rate
             * @description Trading fee rate (e.g., 0.001 for 0.1%)
             */
            fee_rate: number | string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallOfFameResponse */
        HallOfFameResponse: {
            top_profit?: components["schemas"]["RankingEntry"] | null;
            top_loss?: components["schemas"]["RankingEntry"] | null;
            top_volume?: components["schemas"]["RankingEntry"] | null;
            top_win_rate?: components["schemas"]["RankingEntry"] | null;
            top_fees?: components["schemas"]["RankingEntry"] | null;
            top_night?: components["schemas"]["RankingEntry"] | null;
        };
        /** IpoCreate */
        IpoCreate: {
            /**
             * Quantity
             * @description 발행 주식 수
             */
            quantity: number | string;
            /**
             * Initial Price
             * @description 초기 희망 가격 (평단가로 설정됨)
             * @default 0
             */
            initial_price: number | string;
            /**
             * Dividend Rate
             * @description 배당률 (0.0 ~ 1.0)
             */
            dividend_rate: number | string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * MarketState
         * @enum {string}
         */
        MarketState: "OPEN" | "CLOSED" | "PRE_MARKET" | "AFTER_MARKET";
        /** MarketStatusResponse */
        MarketStatusResponse: {
            krx: components["schemas"]["MarketState"];
            us: components["schemas"]["MarketState"];
            crypto: components["schemas"]["MarketState"];
            /** Server Time */
            server_time: string;
        };
        /**
         * MarketType
         * @enum {string}
         */
        MarketType: "KRX" | "US" | "CRYPTO" | "HUMAN";
        /** MessageTemplateResponse */
        MessageTemplateResponse: {
            /** Key */
            key: string;
            /** Content */
            content: string;
        };
        /** MessageTemplateUpdate */
        MessageTemplateUpdate: {
            /**
             * Key
             * @description Template key (e.g., whale_trade)
             */
            key: string;
            /**
             * Content
             * @description Template content with placeholders
             */
            content: string;
        };
        /** MoverResponse */
        MoverResponse: {
            ticker: components["schemas"]["TickerResponse"];
            /**
             * Price
             * Format: decimal
             */
            price: string;
            /**
             * Change Percent
             * Format: decimal
             */
            change_percent: string;
            /**
             * Volume
             * Format: decimal
             */
            volume: string;
            /**
             * Value
             * Format: decimal
             */
            value: string;
        };
        /** NoticeCreate */
        NoticeCreate: {
            /** Message */
            message: string;
        };
        /** OrderBookEntry */
        OrderBookEntry: {
            /**
             * Price
             * Format: decimal
             */
            price: string;
            /**
             * Quantity
             * Format: decimal
             */
            quantity: string;
        };
        /** OrderBookResponse */
        OrderBookResponse: {
            /** Ticker Id */
            ticker_id: string;
            /** Bids */
            bids: components["schemas"]["OrderBookEntry"][];
            /** Asks */
            asks: components["schemas"]["OrderBookEntry"][];
        };
        /** OrderCreate */
        OrderCreate: {
            /** Ticker Id */
            ticker_id: string;
            side: components["schemas"]["OrderSide"];
            /** Quantity */
            quantity: number | string;
            /** @default MARKET */
            type: components["schemas"]["OrderType"];
            /** Target Price */
            target_price?: number | string | null;
            /** Stop Price */
            stop_price?: number | string | null;
            /** Trailing Gap */
            trailing_gap?: number | string | null;
        };
        /** OrderListResponse */
        OrderListResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker Id */
            ticker_id: string;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /**
             * Quantity
             * Format: decimal
             */
            quantity: string;
            /** Price */
            price?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderResponse */
        OrderResponse: {
            /** Order Id */
            order_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Ticker Id */
            ticker_id?: string | null;
            /** Side */
            side?: string | null;
            /** Type */
            type?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Target Price */
            target_price?: string | null;
            /** Stop Price */
            stop_price?: string | null;
            /** Trailing Gap */
            trailing_gap?: string | null;
            /** Price */
            price?: string | null;
            /** Unfilled Quantity */
            unfilled_quantity?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Fail Reason */
            fail_reason?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Link Id */
            link_id?: string | null;
        };
        /**
         * OrderSide
         * @enum {string}
         */
        OrderSide: "BUY" | "SELL";
        /**
         * OrderType
         * @enum {string}
         */
        OrderType: "MARKET" | "LIMIT" | "STOP_LOSS" | "TAKE_PROFIT" | "STOP_LIMIT" | "TRAILING_STOP";
        /** PnLResponse */
        PnLResponse: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Realized Pnl
             * Format: decimal
             */
            realized_pnl: string;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /**
             * Cash Balance
             * Format: decimal
             */
            cash_balance: string;
            /**
             * Total Asset Value
             * Format: decimal
             */
            total_asset_value: string;
            /** Assets */
            assets: components["schemas"]["AssetResponse"][];
        };
        /** PriceUpdate */
        PriceUpdate: {
            /** Ticker Id */
            ticker_id: string;
            /** Price */
            price: number | string;
        };
        /** RankingEntry */
        RankingEntry: {
            /** Rank */
            rank: number;
            /** Nickname */
            nickname: string;
            /**
             * Value
             * Format: decimal
             */
            value: string;
            /** Extra Info */
            extra_info?: {
                [key: string]: unknown;
            } | null;
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** SeasonResponse */
        SeasonResponse: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
        };
        /** TickerCreate */
        TickerCreate: {
            /** Id */
            id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            market_type: components["schemas"]["MarketType"];
            currency: components["schemas"]["Currency"];
            /** @default UPBIT */
            source: components["schemas"]["TickerSource"];
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** TickerResponse */
        TickerResponse: {
            /** Id */
            id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            market_type: components["schemas"]["MarketType"];
            currency: components["schemas"]["Currency"];
            /** Is Active */
            is_active: boolean;
            /** Source */
            source: string;
        };
        /**
         * TickerSource
         * @enum {string}
         */
        TickerSource: "UPBIT" | "MOCK" | "TEST";
        /** TickerUpdate */
        TickerUpdate: {
            /** Symbol */
            symbol?: string | null;
            /** Name */
            name?: string | null;
            market_type?: components["schemas"]["MarketType"] | null;
            currency?: components["schemas"]["Currency"] | null;
            source?: components["schemas"]["TickerSource"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            /** Badges */
            badges: {
                [key: string]: unknown;
            }[];
            /** Profit Rate */
            profit_rate?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Nickname */
            nickname: string;
            /** Is Active */
            is_active: boolean;
            /** Badges */
            badges: {
                [key: string]: unknown;
            }[];
        };
        /** UserStatusUpdate */
        UserStatusUpdate: {
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalletTransactionHistory */
        WalletTransactionHistory: {
            /**
             * Prev Balance
             * Format: decimal
             */
            prev_balance: string;
            /**
             * New Balance
             * Format: decimal
             */
            new_balance: string;
            /** Reason */
            reason?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Wallet Id
             * Format: uuid
             */
            wallet_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            ticker: components["schemas"]["TickerResponse"];
            /** Current Price */
            current_price: number;
        };
        /** WhaleThresholdUpdate */
        WhaleThresholdUpdate: {
            /**
             * Whale Threshold Krw
             * @description Whale alert threshold in KRW
             */
            whale_threshold_krw: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_current_user_me_api_v1_auth_login_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    login_access_token_api_v1_auth_login_access_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_access_token_api_v1_auth_login_access_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_login_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discord_authorize_url_api_v1_auth_discord_authorize_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    discord_exchange_code_api_v1_auth_discord_exchange_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscordExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_portfolio_api_v1_me_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    get_my_watchlist_api_v1_me_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"][];
                };
            };
        };
    };
    add_to_my_watchlist_api_v1_me_watchlist__ticker_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_my_watchlist_api_v1_me_watchlist__ticker_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_wallet_history_api_v1_me_wallet_history_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletTransactionHistory"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_pnl_api_v1_me_pnl_get: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                start: string;
                /** @description End date (YYYY-MM-DD) */
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_orders_api_v1_me_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"][];
                };
            };
        };
    };
    get_my_open_orders_api_v1_me_orders_open_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"][];
                };
            };
        };
    };
    get_my_order_detail_api_v1_me_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_bankruptcy_api_v1_me_bankruptcy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_v1_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_status_api_v1_market_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStatusResponse"];
                };
            };
        };
    };
    get_tickers_api_v1_market_tickers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"][];
                };
            };
        };
    };
    search_tickers_api_v1_market_search_get: {
        parameters: {
            query: {
                /** @description 종목 이름 또는 심볼 검색어 */
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candles_api_v1_market_candles__ticker_id__get: {
        parameters: {
            query?: {
                interval?: string;
                limit?: number;
            };
            header?: never;
            path: {
                ticker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orderbook_api_v1_market_orderbook__ticker_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderBookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticker_current_price_api_v1_market_price__ticker_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                ticker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentPriceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_movers_endpoint_api_v1_market_movers_get: {
        parameters: {
            query: {
                type: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoverResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trending_endpoint_api_v1_market_trending_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoverResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seasons_api_v1_rankings_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonResponse"][];
                };
            };
        };
    };
    get_hall_of_fame_api_v1_rankings_hall_of_fame_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOfFameResponse"];
                };
            };
        };
    };
    get_rankings_api_v1_rankings__ranking_type__get: {
        parameters: {
            query?: {
                /** @description 조회할 시즌 ID (생략 시 현재 활성 시즌) */
                season_id?: number;
                limit?: number;
            };
            header?: never;
            path: {
                ranking_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_bailout_api_v1_human_bailout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_ipo_api_v1_human_ipo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IpoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    burn_shares_api_v1_human_burn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BurnCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_ban_status_api_v1_admin_users__user_id__status_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_force_bankruptcy_api_v1_admin_users__user_id__bankruptcy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_system_notice_api_v1_admin_notice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trading_fee_api_v1_admin_fee_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    update_trading_fee_api_v1_admin_fee_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_test_price_admin_api_v1_admin_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_whale_threshold_api_v1_admin_alerts_whale_threshold_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_whale_threshold_api_v1_admin_alerts_whale_threshold_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhaleThresholdUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_admin_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_template_api_v1_admin_templates__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_template_api_v1_admin_templates__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageTemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticker_api_v1_admin_tickers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TickerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticker_api_v1_admin_tickers__ticker_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TickerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ticker_api_v1_admin_tickers__ticker_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_api_keys__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyListResponse"];
                };
            };
        };
    };
    create_api_key_api_v1_api_keys__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_v1_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_api_key_api_v1_api_keys__key_id__rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRotateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_endpoint_api_v1_users__user_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
